name: Build and Deploy - Azure API App
on:
  workflow_dispatch:

jobs:
  build-dotnet:
    name: Build .NET
    runs-on: ubuntu-latest
    env:
      DOTNET_PROJECT: 'WarcraftGearPlanner.Server/WarcraftGearPlanner.Server.csproj'
      DOTNET_CONFIG: 'Release'
      DOTNET_VERSION: '8.0.x'
      DOTNET_ROOT: '/home/runner/.dotnet'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: .NET Setup ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: .NET Build
        run: dotnet build ${{ env.DOTNET_PROJECT }} -c ${{ env.DOTNET_CONFIG }}

      - name: .NET Publish
        run: dotnet publish ${{ env.DOTNET_PROJECT }} -c ${{ env.DOTNET_CONFIG }} -o ${{ env.DOTNET_ROOT }}/warcraft-gear-planner

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/warcraft-gear-planner

  deploy-azure:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build-dotnet
    environment:
      name: 'PROD - API'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wgp-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_PUBLISHPROFILE_WGP_API }}
          package: .