name: Build and Deploy - API Container App
on:
  push:
    branches: 
      [ master ]
    paths:
    - 'WarcraftGearPlanner.Server/**'
    - '.github/workflows/deploy-container-api.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WGPAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WGPAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WGPAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/WarcraftGearPlanner.Server 
          registryUrl: docker.io
          registryUsername: ${{ secrets.WGPAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WGPAPI_REGISTRY_PASSWORD }}
          containerAppName: wgp-api
          resourceGroup: warcraft-gear-planner
          imageToBuild: mturchik/wgp-api:${{ github.sha }}
          dockerfilePath: Dockerfile


