name: Trigger auto deployment for wgp-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'WarcraftGearPlanner.Server/**'
    - '.github/workflows/wgp-api-AutoDeployTrigger-f900842e-dddd-445e-ba0b-d27995c9e491.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WGPAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WGPAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WGPAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: docker.io
          registryUsername: ${{ secrets.WGPAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WGPAPI_REGISTRY_PASSWORD }}
          containerAppName: wgp-api
          resourceGroup: warcraft-gear-planner
          imageToBuild: mturchik/wgp-api:${{ github.sha }}
          dockerfilePath: WarcraftGearPlanner.Server/Dockerfile


